### ISSUE TITLE
Still getting redirected? Do they update like every 2 hrs or something?

### ISSUE THREAD

**Issue by PandaLif3** [hrt/WheelChair#10]
1.8.6 came out, not sure if that's what caused it again?

**Comment by chrisboyy** [comment]
im still getting re-directed also, it was working for about 4 hours, and now its not

**Comment by RussianCrew** [comment]
It is not working for me.

**Comment by wagegap** [comment]
I am unable to do the setup for the one you wanted me to use in the mean time, I dont know how to explain it just try it out for your self

**Comment by AyyyItzLoilPop** [comment]
It's redirecting here AGAIN

**Comment by hrt** [comment]
updated.
