### ISSUE TITLE
HRT: PLEASE LOOK AT THIS!

### ISSUE THREAD

**Issue by lukeacat** [hrt/WheelChair#121]
hey hrt, i'm on firefox and the cheat extenstion does not work

also, could you make a discord server or is there any way I could contact you?

**Comment by hrt** [comment]
@kuteshiki

Use chrome. I work on anti anti cheat under the assumption that this is a chromium extension.

Regarding contacting me, I advise against it as I do not enjoy getting bothered for tech support.
