### ISSUE TITLE
 HRT: check this again!

### ISSUE THREAD

**Issue by lukeacat** [hrt/WheelChair#123]
I'm not asking for tech support. I'm a fellow JS dev and I would like to help
I'm not using chrome due to exessive cpu usage and slowly transfering from Google products. Do you know a way to compile a firefox extenstion?
I (when this worked on Violentmonkey) made a working Antiaim/rage that worked.

(i'm not native english/american sorry for spelling)

**Comment by hrt** [comment]
Like i said, a lot of the anti anti cheat I've implemented builds ontop of the assumption it's run on a Chromium browser. There is no simple way to get it working on Firefox without changing and verifying a lot of the already written code.
