### ISSUE TITLE
esp/wallhack code to paste into console pls

### ISSUE THREAD

**Issue by arthurauffray** [hrt/WheelChair#129]
Hey Inusha, just wondering can you provide the code for the wallhack/esp that we could just paste into the console?
I tried copying and pasting what you sent me last time but it didn't work. I fixed some issues with brackets and also tried minifying it; none worked.

**Comment by hrt** [comment]
As it is, it won't work (copy paste into console esp) and I won't be maintaining anything krunker related outside of this repository.
