### ISSUE TITLE
Bug/Glitch i dont know

### ISSUE THREAD

**Issue by WheelChairUser420** [hrt/WheelChair#134]
So when I was using the sniper class it aimed in my sniper for a couple seconds and I couldn't unaim it  and it didn't shoot properly and it resulted in me getting killed, this is quite annoying and I was wondering if you knew about it.

**Comment by hrt** [comment]
Won't unscope until target is dead (since it takes extra time to rescope).
Bullets missing is because Krunkers net code is garbage, so cheat requires velocity based prediction which it doesn't have.
