### ISSUE TITLE
Please update the script

### ISSUE THREAD

**Issue by wagegap** [hrt/WheelChair#14]
Krunker updated so now the script is one version behind and cant be used

**Comment by RussianCrew** [comment]
Then how do I use it then?

**Comment by IlSnowIl** [comment]
u can't

**Comment by PandaLif3** [comment]
use this for the time being https://github.com/MasterP-kr/WheelChair

**Comment by wagegap** [comment]
I am unable to finish the setup what do I do?

**Comment by hrt** [comment]
updated.
