### ISSUE TITLE
I keep getting the message "Disconnected"

### ISSUE THREAD

**Issue by Bignate4Slayer** [hrt/WheelChair#153]
please look into this

![image](https://user-images.githubusercontent.com/57815620/71220465-2afac780-228e-11ea-961e-007ac7489c80.png)

**Comment by hrt** [comment]
Remove all exisiting scripts.
Download the latest extension
Navigate to chrome://extensions
Enable developer mode (probably a checkbox in the top right)
Drag the downloaded file into the extensions page (you do not need to extract)
