### ISSUE TITLE
New version 1.8.7

### ISSUE THREAD

**Issue by ZaresPlusX** [hrt/WheelChair#18]
1.8.7 now

**Comment by AyyyItzLoilPop** [comment]
yeah XD

**Comment by hrt** [comment]
https://github.com/hrt/WheelChair/issues/20

**Comment by ZaresPlusX** [comment]
Thanks m8.
Take your time.

**Comment by ThePoizy** [comment]
if i get it, it will be 20:00?

**Comment by Rurzofy** [comment]
i think so

**Comment by ThePoizy** [comment]
still nothing:(

**Comment by relative2** [comment]
stop complaining and update it yourself

**Comment by ThePoizy** [comment]
i know, its very hard sorry:)

**Comment by Rurzofy** [comment]
gay

**Comment by 0001-1** [comment]
i'm there to use your hacks even though i don't use them much!

**Comment by hrt** [comment]
done
