### ISSUE TITLE
Auto fire

### ISSUE THREAD

**Issue by soma811** [hrt/WheelChair#19]
Do you think you could release a script with your 1.8.7 update without the auto fire mechanic (only aim-bot, speed, jump, and wall-hacks)?

**Comment by hrt** [comment]
That's not a change that I'd want considering it reduces the scripts performance in hack v hack.

I'm sure variants of this repo have a menu where you can disable auto fire mechanic though. Most notably MasterPs fork of this repo.

**Comment by soma811** [comment]
Im asking if you might be able to release 2 scripts one with auto fire one without, or would that be too much work
