### ISSUE TITLE
Patched.

### ISSUE THREAD

**Issue by xKeksbyte** [hrt/WheelChair#2]
Its now 1.8.3 & if you move, You get fart sounds with the script if you move + You only do per shot only 2-10damage without cheat normal damage & the fart sounds are gone

**Comment by xKeksbyte** [comment]
+ got Autobanned so i would recomondeed before you test to logout of your account

**Comment by hrt** [comment]
This repo uses [FunctionHook bypass](https://github.com/hrt/KrunkerBypass/) which krunker targeted in 1.8.3

Head over to [masterPs fork](https://github.com/MasterP-kr/WheelChair) for an alternative bypass and menu whilst I fix up FunctionHook

**Comment by xKeksbyte** [comment]
nvm unpatched it already ;) xd

**Comment by xKeksbyte** [comment]
i've fixed it so idc lol
