### ISSUE TITLE
 When can i download it?

### ISSUE THREAD

**Issue by marcoschoettelkotte** [hrt/WheelChair#23]

**Comment by ThePoizy** [comment]
u need to wait for updated version

**Comment by marre777** [comment]
but when is that tho ive waited for so long

**Comment by ThePoizy** [comment]
idk

**Comment by spookingtons** [comment]
usually its out at 3:00 for me its kinda late but this man got a life guys
leave him be, cuz he definitley wasnt made just to make krunker hacks online lmao

**Comment by hrt** [comment]
done
