### ISSUE TITLE
The Game will disconnect me

### ISSUE THREAD

**Issue by marcoschoettelkotte** [hrt/WheelChair#25]

**Comment by marcoschoettelkotte** [comment]
after 30seconds in a round i will been kicked

**Comment by hrt** [comment]
Some people get it some don't.
I'll figure it out later if it's the script

**Comment by hrt** [comment]
Update: i have an idea, will fix tomorrow

**Comment by Canodox** [comment]
Se me desconecta después de un tiempo muy corto

**Comment by Canodox** [comment]
My game is disconnected in a very short time

**Comment by HITIII** [comment]
yea disconnects every 30 sec. dont worry tho, hrt is a pro

**Comment by hrt** [comment]
dc fixed, update your script and disable ad block
