### ISSUE TITLE
The aimbot

### ISSUE THREAD

**Issue by marre777** [hrt/WheelChair#27]
i have noticed that it just shoots and if someone comes behind me it dosent even aim for it it just kills him. beside the disconnect issue i also think its more detectable. Also it dosent have the same accuracy as the old one. it was much better. will you fix?

**Comment by hrt** [comment]
1. that's called silent aim and has always been part of the cheat and isn't any more detectable at the moment
2. I'm gonna push a fix for disconnect issue
3. Aimbot logic is literally untouched.. Unless you changed PC or krunker changed how their game plays for you it should be the same.

**Comment by hrt** [comment]
dc fixed, update your script and disable ad block
