### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by Sadykhzadeh** [hrt/WheelChair#29]
![image](https://user-images.githubusercontent.com/51178055/68528596-52b15400-030e-11ea-9396-e19dae4c8ef6.png)

**Comment by hrt** [comment]
Show console (f12)

**Comment by Sadykhzadeh** [comment]
![image](https://user-images.githubusercontent.com/51178055/68528638-dcf9b800-030e-11ea-9f02-50b036cc022b.png)

**Comment by hrt** [comment]
maybe disable ad block and show again

**Comment by ZayLoreX** [comment]
how do you load mod menu?

**Comment by Sadykhzadeh** [comment]
> maybe disable ad block and show again

Yup, i did it

![image](https://user-images.githubusercontent.com/51178055/68533644-bbb3be80-0344-11ea-9d38-68ddd02f92a9.png)

Am I only one person who have that problem? :(

**Comment by hrt** [comment]
Pretty sure you are. Which browser?
Disable all other ad ons and scripts.

**Comment by Sadykhzadeh** [comment]
Opera GX Browser
Other scripts are disable, i run only your script
there were no problem yesterday

**Comment by hrt** [comment]
Try updating the script and if it still fails a different browser.

**Comment by Sadykhzadeh** [comment]
Fix bug in Opera
Thanks! :)
