### ISSUE TITLE
please make 1.8.9 fast before it is installed

### ISSUE THREAD

**Issue by ahmadthetatertot** [hrt/WheelChair#32]
please

**Comment by hrt** [comment]
I don't understand the issue. It is still 1.8.8

**Comment by marre777** [comment]
i think he wants the new verson done before the krunker version so the seacond 1.8.9 is updated you can release the new working hack.

**Comment by hrt** [comment]
How can I react to anti cheat patching this specific script before they release the patch

**Comment by hrt** [comment]
I mean I can sort of but it's like giving away my secrets to anti cheats

**Comment by mixelx** [comment]
is it possible to make aimbot's reaction a bit faster?

**Comment by hrt** [comment]
perhaps but what's the point lol

**Comment by mixelx** [comment]
I just played using this cheat and there was another guy also cheating. I guess he was using another cheat, because I killed him just like in 1 of 10 situations

**Comment by hrt** [comment]
because you don't know the technique of hack v hack, peeking is over powered

you can almost guarantee everyone is using the same  cheat
