### ISSUE TITLE
Silent aim

### ISSUE THREAD

**Issue by Themaninsuit** [hrt/WheelChair#35]
Silent aim messes with my movement skill preventing me from bhopping, when silent aim is turned off if my character turns around at least it shows me that my character is turned. If you do not know what i mean ill give you an example. Imagine i am running forward and someone is behind me silent aim turns my body but not my face resulting me in walking backward and putting me in the line of fire of soeone else before i can shoot the one behind me. this is very situational but it happened almost every game. allow people to turn it on or off please.

**Comment by hrt** [comment]
This is somewhat intentional.
With or without silent aim - you will move towards the direction of the target.

Silent aim just aims on to enemies without locking your camera onto them.


In terms of adding the option to turn it off, I don't feel like adding a menu so probably not.

**Comment by Themaninsuit** [comment]
without silent aim i can adjust my movement with it i dont know that im looking moving somewhere else. your probably a busy man and i respect that but alot of people can sing the same song i am as in they can tell you the same thing is messing with them. 

no need to reply
