### ISSUE TITLE
More "legit" version?

### ISSUE THREAD

**Issue by ghost** [hrt/WheelChair#36]
Will you be making a separate more legit cheat of this? For example, aimbotting players you see in the direction you are facing instead of behind or a triggerbot? Thanks for your work!

**Comment by hrt** [comment]
You're mistaken if you think I released this to promote cheating, especially "legit" cheating.

I used to enjoy hack versus hack but now I don't enjoy or play the game at all outside of the anti cheat cycle which requires my cheat to be public for them to react.
