### ISSUE TITLE
Aimbot player whitelist/blacklist

### ISSUE THREAD

**Issue by Miner1834** [hrt/WheelChair#41]
Hi! I only want to use hacks against certain players(other hackers or toxic people) while playing legit against others. Is there a way to make the aimbot only activate on certain people? 
Thanks! 
Also is there a way to put the sniper scope on other weapons(long-range shooting without aimbot)?

**Comment by hrt** [comment]
Used to be able to select which players on an older script but this one has never come with the ability to configure. You raise a decent point but it's effort I'm not willing to put in considering I don't play the game anymore and it would come with detection vectors which would need covering.
