### ISSUE TITLE
1.8.9?

### ISSUE THREAD

**Issue by Rhino20** [hrt/WheelChair#43]

**Comment by AyyyItzLoilPop** [comment]
we need new version xD

**Comment by BattingTundra75** [comment]
yes

**Comment by hrt** [comment]
Game update. Script will redirect you here until I have updated it.
I suggest disabling the script. I will likely begin updating in 14 hours.

**Comment by BattingTundra75** [comment]
> Game update. Script will redirect you here until I have updated it.
> I suggest disabling the script. I will likely begin updating in 14 hours.

so will u finish the hack update in 14 hours is that what ur saying

**Comment by DaBaldEagul** [comment]
No, he will START in (now) 12 hours.

**Comment by Ponyskalambu** [comment]
yup he start the update in 7 hours guys

**Comment by BattingTundra75** [comment]
> Game update. Script will redirect you here until I have updated it.
> I suggest disabling the script. I will likely begin updating in 14 hours.

Are u finished making the code

**Comment by jeannilson** [comment]
so he is making the script now(maybe). it will take a while but please be patient if you guys keep annoying him he will take much longer

**Comment by hrt** [comment]
Update done. Remove the old script
