### ISSUE TITLE
I cant connect to the game

### ISSUE THREAD

**Issue by Tripeks** [hrt/WheelChair#44]
When i click on Krunker.io then it will pop up this site, well what should i do?

**Comment by hrt** [comment]
Disable my script until the game has updated

**Comment by BattingTundra75** [comment]
still hasnt fixed

**Comment by BattingTundra75** [comment]
is it a new version is that why because when ever i open krunker it directs me to this website

**Comment by whatwhyletmeconnect** [comment]
wait what you guys probobly need a new code he is probobley updating it right now as we speak so like every 10 min enter in the code

**Comment by hrt** [comment]
Game update. Script will redirect you here until I have updated it.
I suggest disabling the script. I will likely begin updating in 14 hours.

**Comment by whatwhyletmeconnect** [comment]
go to this problem > wait what you guys probobly need a new code he is probobley updating it right now as we speak so like every 10 min enter in the code #46

**Comment by WinterShip28659** [comment]
How long ntil update??

**Comment by hrt** [comment]
Update done. Remove the old script
