### ISSUE TITLE
Keeps directing me to this site

### ISSUE THREAD

**Issue by BattingTundra75** [hrt/WheelChair#45]
Hey is it because its a new version or not i dont know why it keeps directing me here

**Comment by ItsCasuals** [comment]
yes same here keeps redirectin me to this site

**Comment by whatwhyletmeconnect** [comment]
wait what you guys probobly need a new code he is probobley updating it right now as we speak so like every 10 min enter in the code

**Comment by BattingTundra75** [comment]
> wait what you guys probobly need a new code he is probobley updating it right now as we speak so like every 10 min enter in the code

Enter what code do u mean the hack thing

**Comment by whatwhyletmeconnect** [comment]
well

**Comment by whatwhyletmeconnect** [comment]
i want to know someting is this like a chat

**Comment by whatwhyletmeconnect** [comment]
yeah whatever
so basiclly you should go thorugh the hakc and see what is rederecting you to the website

**Comment by whatwhyletmeconnect** [comment]
is anyone here? ok comment if you are here

**Comment by michaelshumshum** [comment]
i am looking through the code and nothing seems to be the problem

**Comment by whatwhyletmeconnect** [comment]
hmm then i might have a look and i might be able to find something if not i can give you and another hack and you need to delete a part in that one but . i am not sure it works

**Comment by hrt** [comment]
Game update. Script will redirect you here until I have updated it.
I suggest disabling the script. I will likely update in 14 hours.

**Comment by michaelshumshum** [comment]
ok then bro

**Comment by BattingTundra75** [comment]
> Game update. Script will redirect you here until I have updated it.
> I suggest disabling the script. I will likely update in 14 hours.

ok sure

**Comment by whatwhyletmeconnect** [comment]
go to this problem

**Comment by whatwhyletmeconnect** [comment]
> wait what you guys probobly need a new code he is probobley updating it right now as we speak so like every 10 min enter in the code #46

**Comment by BattingTundra75** [comment]
Should be 11 hours until we start hacking again

**Comment by BattingTundra75** [comment]
> Game update. Script will redirect you here until I have updated it.
> I suggest disabling the script. I will likely update in 14 hours.

Well its 1 hour left but I noticed that his location is in Sri Lanka and right now its 2:00am so I doubt he will be up maybe 5 hours then and he would be up to update code. Everyone be patience and thank this guy for making this epic hack without being payed

**Comment by hrt** [comment]
Update done. Remove the old script
