### ISSUE TITLE
> wait what you guys probobly need a new code he is probobley updating it right now as we speak so like every 10 min enter in the code

### ISSUE THREAD

**Issue by whatwhyletmeconnect** [hrt/WheelChair#46]
> wait what you guys probobly need a new code he is probobley updating it right now as we speak so like every 10 min enter in the code

Enter what code do u mean the hack thing

_Originally posted by @BattingTundra75 in https://github.com/hrt/WheelChair/issues/45#issuecomment-553767745_

**Comment by whatwhyletmeconnect** [comment]
so we need to get a thign going we need every one to go and  do a  twitch stream and we need to find out what is making  this happen if you are going ot join in a youtube / mixer / twitch stream i will at some point hot all the twitch and mixer streams on one stream if you are going to stream comment your name and i will watch you you need a mic or some why of talking thx and  i can not do youtube is because copyright duh so plz have as meny people join to get this working the owner said it is going to take 14 hours no we will get it working

**Comment by michaelshumshum** [comment]
if u want to do this so badly, just discord

**Comment by whatwhyletmeconnect** [comment]
i dont have discord

**Comment by michaelshumshum** [comment]
twitch is will take too long and is not reliable. making a discord account is way easier than a twitch account.

**Comment by whatwhyletmeconnect** [comment]
well i tried to help i qwuit

**Comment by hrt** [comment]
Update done. Remove the old script
