### ISSUE TITLE
1.8.9 User script will be ready in 11 hours about

### ISSUE THREAD

**Issue by ItsCasuals** [hrt/WheelChair#50]

**Comment by TristanJS** [comment]
bet

**Comment by imditto** [comment]
when was this posted

**Comment by imditto** [comment]
are you shitting me

**Comment by maarker** [comment]
Hey, where can i find the script after its done ?

**Comment by codeacex223** [comment]
i need the script

**Comment by PatheticMustan** [comment]
You can update it from tampermonkey, for now please just play Krunker WITHOUT HACKS. What a nightmare, legitimately playing the game, right?

**Comment by hameem-2006** [comment]
why cant i open krunker

**Comment by RaulSeganfreddo** [comment]
@hameem-2006 because you have tampermonkey enabled, the script is outdated so it redirect you here. Disable tampermonkey and you can play krunker, without the script obv. You have to wait till they update the script for the 1.8.9 version of the game.

**Comment by maarker** [comment]
> @hameem-2006 because you have tampermonkey enabled, the script is outdated so it redirect you here. Disable tampermonkey and you can play krunker, without the script obv. You have to wait till they update the script for the 1.8.9 version of the game.

now its closed even if you have tampermonkey disabled sooo... idk

**Comment by hameem-2006** [comment]
yo is the krunker updating to season 2??? is that the reason krunker is taking forever to load

**Comment by maarker** [comment]
> yo is the krunker updating to season 2??? is that the reason krunker is taking forever to load

i dont know, it is possible i guess

**Comment by RIOTSc0p3Z-OFFICIAL** [comment]
> yo is the krunker updating to season 2??? is that the reason krunker is taking forever to load

no you numb nuts its 1.8.9 read the bottom left

**Comment by RayTheGod12** [comment]
The script isn't done lmao. that's a bunch of lies

**Comment by jeannilson** [comment]
@RayTheGod12 he said he will start working on it in 11hour so 11hour has passed so he is now making it

**Comment by hrt** [comment]
Update done. Remove the old script
