### ISSUE TITLE
yo why the fuck can't i open krunker 

### ISSUE THREAD

**Issue by imditto** [hrt/WheelChair#51]

**Comment by FreedTapestry21** [comment]
You can't open krunker that's right!
I think he's working on a new hack.
Screenshot:

![Screenshot 2019-11-14 at 15 03 41](https://user-images.githubusercontent.com/57751291/68863597-f96f6900-06ef-11ea-9bbf-95aecb8de14a.png)

**Comment by Ponyskalambu** [comment]
the owner of the script will update the script in 7 hours

**Comment by hameem-2006** [comment]
why cant i play krunker

**Comment by michaelshumshum** [comment]
> why cant i play krunker

do u even fucking read

**Comment by Zwaia** [comment]
So the maker of the script is updating it and that's why we can't play?

**Comment by FreedTapestry21** [comment]
Yes, because krunker had a update and the hack didn’t work so he is fixing it

**Comment by Ponyskalambu** [comment]
Of you delete the script from Tamper monkey u can play man

**Comment by hameem-2006** [comment]
yo is the krunker updating to season 2??? is that the reason krunker is taking forever to load

**Comment by BattingTundra75** [comment]
Can't u bloody read imditto just be wait jesus christ

**Comment by whatwhyletmeconnect** [comment]
> > why cant i play krunker
> 
> do u even  read 
Wtf why are you going and being mean ya num but

**Comment by whatwhyletmeconnect** [comment]
Also wait Evry one colse it

**Comment by hrt** [comment]
Update done. Remove the old script
