### ISSUE TITLE
the only issue with this code are the people complaining about it

### ISSUE THREAD

**Issue by michaelshumshum** [hrt/WheelChair#52]
just be patient and let the dude finish the code. stop making more and more issue requests.

**Comment by hameem-2006** [comment]
exactly

**Comment by hrt** [comment]
There has been 50,000+ hits on this repo today of which 5,000+ were unique. This is somewhat expected.

**Comment by 24marsots** [comment]
whats the problem it wont let me use the code

**Comment by hameem-2006** [comment]
yo is the krunker updating to season 2??? is that the reason krunker is taking forever to load.

**Comment by hrt** [comment]
@hameem-2006 Krunkers been down for a bit apparently

**Comment by Zwaia** [comment]
Yup krunker won't work for me too

**Comment by 24marsots** [comment]
but does the code work

**Comment by Zwaia** [comment]
Hrt is updating the code, that means it don't work now. And anyways you wouldn't be able to play even if the code worked because krunker is down.

**Comment by 24marsots** [comment]
went will it be fixed

**Comment by 24marsots** [comment]
this was an op code

**Comment by Zwaia** [comment]
He will start updating it in about 3 hours or something like that

**Comment by 24marsots** [comment]
ok thanks and is i true that krunker is putting out battle royal

**Comment by maarker** [comment]
krunker is online again

**Comment by whatwhyletmeconnect** [comment]
but the code is not working
just went on

**Comment by hrt** [comment]
still down for me.

**Comment by whatwhyletmeconnect** [comment]
so is anyone relised that there is invisable hack in this as there is also aimbot esp

**Comment by whatwhyletmeconnect** [comment]
refresh

**Comment by maarker** [comment]
well, its offline again xD

**Comment by whatwhyletmeconnect** [comment]
What he heck

**Comment by whatwhyletmeconnect** [comment]
Dang

**Comment by 24marsots** [comment]
do you have the code up

**Comment by maarker** [comment]
@hrt do you know when its gonna be done ? circa ?

**Comment by BattingTundra75** [comment]
when will u do the hack

**Comment by hrt** [comment]
Update done. Remove the old script
