### ISSUE TITLE
When is the script done?

### ISSUE THREAD

**Issue by MeAvEMoose** [hrt/WheelChair#54]
BY when is the script is going to be done for krunker?

**Comment by RayTheGod12** [comment]
Krunker doesn't work just unenable tamper and it should work, if I still isn't working for you, I have no idea.

**Comment by tommyakashi** [comment]
@RayTheGod12 We are trying to get aimbot not just play the game

**Comment by tommyakashi** [comment]
@hrt when is the script going to be done?

**Comment by hrt** [comment]
Update done. Remove the old script
