### ISSUE TITLE
It's been 11 Hours + I know i'm kinda pushing it but you did say it would be done in 11 hours

### ISSUE THREAD

**Issue by RayTheGod12** [hrt/WheelChair#55]

**Comment by tommyakashi** [comment]
i know righht

**Comment by hrt** [comment]
https://github.com/hrt/WheelChair/issues/64#issuecomment-554280375

**Comment by hrt** [comment]
I didn't expect the game to still be down when I tried looking at it.

**Comment by hrt** [comment]
Update done. Remove the old script
