### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by IceHacks** [hrt/WheelChair#59]
A dude (CrazyHoodlem#1903) told me to come here and ask if you needed help. Do you? I just found out my krunker cheat (I don't play krunker) was broke. But I found the problem. Feel free to contact me at IceIceBaby#2875 if you want info. This updates' anticheat was not as advanced as I hoped.

**Comment by tommyakashi** [comment]
could you please tell me

**Comment by hrt** [comment]
No I just prioritize real life over updating for krunker and when I did have time the game was down.

**Comment by IceHacks** [comment]
ok
