### ISSUE TITLE
Getting re-directed

### ISSUE THREAD

**Issue by chrisboyy** [hrt/WheelChair#6]
This hack was working perfectly fine yesterday when I was playing krunker. But today all of a sudden, it seems to be re-directing me to this page when I open up krunker. I do not know why this is happening. If you could please tackle this problem or let me know if there is something I have to do to get it to not re-direct me again.

**Comment by dasdasdasdqw** [comment]
same thing happens to me.

> This hack was working perfectly fine yesterday when I was playing krunker. But today all of a sudden, it seems to be re-directing me to this page when I open up krunker. I do not know why this is happening. If you could please tackle this problem or let me know if there is something I have to do to get it to not re-direct me again.

**Comment by Gonzax468** [comment]
I know right same, exactly same thing happened to me, it was working perfectly  yesterday, and I just opened **krunker.io** and got redirected to this page **https://github.com/hrt/wheelchair**. I need help please, I also tried deleting the hack off my tamper monkey dashboard and recopied the link to another new script. Same thing happened.

**Comment by Rocky299579** [comment]
The creator said he would update it, in about 10 hours. The reason it doesnt work is because krunker has a new version

**Comment by hrt** [comment]
https://github.com/hrt/WheelChair/issues/5

**Comment by hrt** [comment]
updated.
