### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by JaxKazuto** [hrt/WheelChair#61]
I didn't want to be like everyone else but I'm dying here can we please get an ETA on the code

**Comment by whatwhyletmeconnect** [comment]
yeah

**Comment by whatwhyletmeconnect** [comment]
THAY ARE UPDATING AGAIN

**Comment by hameem-2006** [comment]
@whatwhyletmeconnect when are we getting the 1.8.9 script/code. Any ideas

**Comment by hrt** [comment]
https://github.com/hrt/WheelChair/issues/64#issuecomment-554280375

**Comment by hrt** [comment]
Update done. Remove the old script
