### ISSUE TITLE
When ?

### ISSUE THREAD

**Issue by FixShadow** [hrt/WheelChair#64]
When to release 1.8.9 ???

**Comment by whatwhyletmeconnect** [comment]
when the update

**Comment by FixShadow** [comment]
that's what i'm asking

**Comment by hameem-2006** [comment]
me too

**Comment by FreedTapestry21** [comment]
me too

**Comment by hrt** [comment]
Lol another 12 hours assuming krunker is not down

**Comment by hameem-2006** [comment]
you mean you will update the game in 12 hours

**Comment by codeacex223** [comment]
plz i need hacks

**Comment by hrt** [comment]
update done. reinstall
