### ISSUE TITLE
New script not working

### ISSUE THREAD

**Issue by shoomoo256** [hrt/WheelChair#65]
i try to use the script but it does the same thing as it was yesterday, it send me here

**Comment by fslinnings** [comment]
Same thing happened to me

**Comment by boi-png** [comment]
let the dud work

**Comment by shoomoo256** [comment]
another thing i tried using hacks and i lost everything i had even though they werent working

**Comment by hrt** [comment]
Maybe because the script has not been updated yet.
Still not home. ETA 5-6 hours

**Comment by hameem-2006** [comment]
hey @hrt whats up all good

**Comment by 24marsots** [comment]
i cant what

**Comment by dioni1212** [comment]
Can Stop The Wither

**Comment by dioni1212** [comment]
ops

**Comment by dioni1212** [comment]
why i type krunker in google and it gois to github can someone help me???

**Comment by jeannilson** [comment]
@dioni1212 disable tamper

**Comment by hrt** [comment]
done
