### ISSUE TITLE
blatant

### ISSUE THREAD

**Issue by SorForr** [hrt/WheelChair#70]
hi the new 1.8.9 hack doesnt have a modmenu? which means its just that one blatant mode. i wanted to use silentaim so i dont get reported and also its not fun that its super blatant. i like to give the people a chance and feel im good at the game. in the 1.8.8 mode there was a silentaim but now there isnt please help!

**Comment by Zwaia** [comment]
Anyway what's silent aim?

**Comment by Zwaia** [comment]
And he already said making a menu was a waste of time and that he wasn't gonna make one

**Comment by SorForr** [comment]
silent aim is like just a cheat that helps your aim
