### ISSUE TITLE
xray needs an update

### ISSUE THREAD

**Issue by Bignate4Slayer** [hrt/WheelChair#71]
the xray feature only shows enemies (sometimes), witch is fine. but sometimes is shows only teammates (not including outline witch is shown on all players). it is good to know what weapon someone has so plz update.

**Comment by HITIII** [comment]
That's a really minor problem. Good job on always keeping up to date Inusha

**Comment by hameem-2006** [comment]
Inusha is the best. The best guy i have met in my entire life

**Comment by hrt** [comment]
lmao

known issue but I don't play enough (only open up krunker when they update) to bother fixing.
