### ISSUE TITLE
krunker

### ISSUE THREAD

**Issue by pringlecans** [hrt/WheelChair#75]
every time i load krunker it loads me to this page and doesent let me play krunker

**Comment by j896** [comment]
same

**Comment by hrt** [comment]
maybe remove the old script and install the new one

and remove all other scripts

**Comment by epicgamer69095** [comment]
mine wont work either i have deleted and re created like 150 times and it still brings me to this page

**Comment by hrt** [comment]
how hard is it to remove existing scripts and install the new damn script from this repository.
