### ISSUE TITLE
Is there a diffrence in using the new extention and using the old user script for tampermonkey?

### ISSUE THREAD

**Issue by ghost** [hrt/WheelChair#85]

**Comment by hrt** [comment]
From your perspective. with the extension you won't have to reinstall if I update.

From anti cheat perspective, it's far more difficult to detect.

**Comment by ghost** [comment]
what about your perspective, isint it harder to code an extension than a userscript?

**Comment by hrt** [comment]
No it gives me more freedom than user scripts
