### ISSUE TITLE
So how do I use this hack now,can I still use tampermpnkey?

### ISSUE THREAD

**Issue by siryeet539** [hrt/WheelChair#87]

**Comment by hrt** [comment]
I don't want to maintain support for tamper monkey when it's inferior to the extension.
Follow the read me

**Comment by siryeet539** [comment]
Sorry for my stupidity but could you send a link to the part where I drag the zip?

**Comment by hrt** [comment]
you drag it into the extensions page 

https://github.com/hrt/WheelChair/blob/master/README.md
