### ISSUE TITLE
Damage per hit is much lower than what it's supposed to be

### ISSUE THREAD

**Issue by TheSwagBros1** [hrt/WheelChair#99]
I played on my account yesterday to notice that the DPH was much lower then what it's supposed to be for every gun. FX: Revolver did only 20 to the head, I isolated the issue to only be on my account. So I'm thinking, does it have something to do with the aimbot itself

**Comment by hrt** [comment]
@TheSwagBros1 your account has been hacker tagged, either manually or by other cheats.
